# Generated by Django 2.0.2 on 2018-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
