# Generated by Django 2.0.2 on 2018-03-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180306_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='seller',
        ),
    ]
