# Generated by Django 2.0.2 on 2018-02-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180225_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='On_Sale',
        ),
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.Users'),
            preserve_default=False,
        ),
    ]
