# Generated by Django 2.0.2 on 2018-03-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
