# Generated by Django 2.0.2 on 2018-02-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
