# Generated by Django 2.0.2 on 2018-03-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180308_1902'),
        ('user', '0009_auto_20180227_1103'),
        ('user', '0006_remove_products_price'),
    ]

    operations = [
    ]
