# Generated by Django 2.0.2 on 2018-02-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180223_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
