# Generated by Django 2.0.2 on 2018-02-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180223_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
