# Generated by Django 2.0.2 on 2018-02-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_users_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='token',
        ),
    ]
