# Generated by Django 2.0.2 on 2018-02-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_users_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='on_sale',
            name='user',
        ),
    ]
